### ISSUE TITLE
How to mask the face during training?

### ISSUE THREAD

**Issue by YoucanBaby** [KohakuBlueleaf/HyperKohaku#12]
Thx for your project!~

I find this sentence in readme: 'Implement better dreambooth training (like masking the face during training)'.

But how to mask the face during training? Eg: random mask 50%?

**Comment by KohakuBlueleaf** [comment]
> Thx for your project!~
> 
> I find this sentence in readme: 'Implement better dreambooth training (like masking the face during training)'.
> 
> But how to mask the face during training? Eg: random mask 50%?

I don't know how to do it either I just know there is something like that
I have no time to read others' source code(

That's why it is in TODO but not Features

**Comment by levi** [comment]
Check out the face mask preprocessing of this PTI repo: https://github.com/replicate/cog-sdxl/blob/main/preprocess.py

**Comment by KohakuBlueleaf** [comment]
@levi Thx for informations
now I know what it does.

**Comment by YoucanBaby** [comment]
> Check out the face mask preprocessing of this PTI repo: https://github.com/replicate/cog-sdxl/blob/main/preprocess.py

Thx for your code~!
